### PR TITLE
Expense preferences

### PR DESCRIPTION
**Pull request by guillaumecabanel**
https://github.com/guillaumecabanel/seazon_at_dojo/issues/8

### CODE REVIEW

**Comment by guillaumecabanel** [comment]
@nfilzi if you have suggestion on how get access to user preference tell me, for know it's not very accessible...

**Comment by nfilzi** [comment]
Just saw your comment, sorry! What do you mean by getting access to user preference?

**Comment by guillaumecabanel** [comment]
access to `/profile/edit` is done by a link on the name in the navbar

**Comment by guillaumecabanel** [comment]
by the way, I will rename profile to preferences, it make more sense I think.

**Pull request merged**
